[project]
name = "django-litestream-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django-litestream>=0.3.0",
    "django>=5.1.4",
    "uvicorn>=0.34.0",
    "whitenoise>=6.8.2",
]
